In [4]:
import torch
import torch.nn.functional as F

# 输入相似性分数 similarity 和标签 labels
similarity = torch.tensor([[2.5, 1.0, 0.5], 
                           [0.2, 1.8, 3.0]])  # 示例数据
labels = torch.tensor([0, 2])  # 示例标签

# similarity = similarity.softmax(-1)

# 使用 F.cross_entropy 计算损失
loss_ce = F.cross_entropy(similarity, labels)

# 使用 F.log_softmax + F.nll_loss 计算损失
log_probs = F.log_softmax(similarity, dim=1)  # softmax + log
loss_nll = F.nll_loss(log_probs, labels)

# 打印两个损失，验证是否相同
print("Loss using F.cross_entropy:", loss_ce.item())
print("Loss using F.log_softmax + F.nll_loss:", loss_nll.item())

# 验证两者是否相等
assert torch.isclose(loss_ce, loss_nll), "The two losses should be identical!"
print("Test passed: The two losses are identical.")


Loss using F.cross_entropy: 0.30765658617019653
Loss using F.log_softmax + F.nll_loss: 0.30765658617019653
Test passed: The two losses are identical.


In [5]:
similarity

tensor([[2.5000, 1.0000, 0.5000],
        [0.2000, 1.8000, 3.0000]])

In [6]:
similarity = similarity.softmax(-1)

similarity

tensor([[0.7361, 0.1643, 0.0996],
        [0.0446, 0.2211, 0.7342]])

In [7]:
similarity = similarity.softmax(-1)

similarity

tensor([[0.4776, 0.2696, 0.2527],
        [0.2389, 0.2850, 0.4761]])

In [50]:
import torch.nn as nn
import torch
image_features, text_features = torch.tensor([[100.0, 78988, 9]], dtype=torch.float), torch.tensor([[[2323.0, 121, 9], [100.0, 12, 300]]], dtype=torch.float)
final_norm = nn.LayerNorm(3)
image_features = final_norm(image_features)
text_features = final_norm(text_features)
image_features, text_features

(tensor([[-0.7059,  1.4142, -0.7083]], grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 1.4129, -0.6539, -0.7590],
          [-0.3098, -1.0401,  1.3499]]], grad_fn=<NativeLayerNormBackward0>))

In [51]:
image_features = final_norm(image_features)
text_features = final_norm(text_features)
image_features, text_features

(tensor([[-0.7059,  1.4142, -0.7083]], grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 1.4129, -0.6539, -0.7590],
          [-0.3098, -1.0401,  1.3499]]], grad_fn=<NativeLayerNormBackward0>))

In [49]:
image_features = torch.nn.functional.normalize(image_features,p=2,dim=1) 
text_features = torch.nn.functional.normalize(text_features,p=2,dim=2)
image_features, text_features

(tensor([[-0.4075,  0.8165, -0.4090]], grad_fn=<DivBackward0>),
 tensor([[[ 0.8157, -0.3775, -0.4382],
          [-0.1789, -0.6005,  0.7794]]], grad_fn=<DivBackward0>))

In [47]:


# image_features: [batch, embedding]
# text_features: [batch, category, embedding]
# output: [batch, category]
similarity = torch.einsum('be,bce->bc', image_features, text_features)
similarity

tensor([[-1.3845, -2.2084]], grad_fn=<ViewBackward0>)

In [37]:
def tyyy(x):
    mean = x.mean()
    std = x.std()
    y = (x - mean) / std
    return y
tyyy(torch.tensor([233.0, 121, 9], dtype=torch.float))


tensor([ 1.,  0., -1.])

In [25]:
import torch
torch.arange(6).reshape(2, 3)[None, 0].shape

torch.Size([1, 3])

In [26]:
[1, 2]*3

[1, 2, 1, 2, 1, 2]